#pragma config(Motor,  port2,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           clawMotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           armMotor,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           frontLeft,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	float xch3Movement;
	float	xch2Movement;
  // User control code here, inside the loop

  while (true)
  {
  	// Get the dedadbanded x and rot values.
  	if( abs(vexRT[Ch3]) > 15 ) {
  		xch3Movement = vexRT[Ch3];
		}
		else {
			xch3Movement = 0;
		}
		if( abs(vexRT[Ch2]) > 15 ) {
			xch2Movement = vexRT[Ch2];
		}
		else {
			xch2Movement = 0;
		}

		// Arcade Drive
		motor[frontRight] = xch2Movement;
		motor[backRight] = xch2Movement;
		motor[frontLeft] = xch3Movement;
		motor[backLeft] = xch3Movement;

		if( vexRT[Btn6U] == 1 ) {
			motor[armMotor] = 127;
		}
		else if( vexRT[Btn6D] == 1 ) {
			motor[armMotor] = -127;
		}
		else {
			motor[armMotor] = 15;
		}

		if( vexRT[Btn5U] == 1 ) {
			motor[clawMotor] = 35;
		}
		else if( vexRT[Btn5D] == 1 ) {
			motor[clawMotor] = -35;
		}
		else {
			motor[clawMotor] = 0;
		}
  }
}
